### ISSUE TITLE
Publish to NPM?

### ISSUE THREAD

**Issue by AnasTawfeek** [WFCD/warframe-drop-data#27]
### Warframe Drops Site Feature Request
---

**Summary (short):**
Publish the package to NPM?

---
**Detailed requirements of the feature**

_As a developer, I'd should be able to install the package from npm._

---
**Mockups:**

-

---

**Additional context**
This project has awesome efforts, and I've got couple ideas that will depend on it, but since we always seek automation, so having this repo as NPM package will be awesome, I could do that, but I believe that the same owners of this repo should own it.

**Comment by TobiTenno** [comment]
It would take a bit of overhaul to outright publish it, and seeing as the files are served, you can always get the most up to date date by requesting the files, how we do over on warframe-status.

**Comment by TobiTenno** [comment]
Ultimately, it's up to @atomicptr. It's easy enough to do, but I'm not sure if it would end up making it more useable compare to how it is now, is my concern.

**Comment by atomicptr** [comment]
I don't see much reason to do this, because the npm version would almost always be outdated when you're using them, mostly because you have to update your own dependencies **and** we have to update them regularly (last part could be automated though). In the end this doesn't add much value and I think you're much better off just requesting the resources via the given endpoints on the fly and update them whenever you feel like it.

**Comment by TobiTenno** [comment]
There are a few ways for updates to be smooth, but it requires a lot more update than it takes to just set up a request to pull all.json once and a while.

**Comment by atomicptr** [comment]
Closing this, because as mentioned it's more efficient to just pull the all.json and cache that however you like.
